### ISSUE TITLE
Tracks being a .json

### ISSUE THREAD

**Issue by vitor9090** [mandaw2014/Rally#3]
Wouldn't be better if the tracks were .json files?

**Comment by mandaw2014** [comment]
Do you mean the model of the track or the python script?

**Comment by ghost** [comment]
It would take like forever to change all of them from .py files to .json files, Plus why? You could've just edited the .py script of them, You don't need .json files.

**Comment by mandaw2014** [comment]
> It would take like forever to change all of them from .py files to .json files, Plus why? You could've just edited the .py script of them, You don't need .json files.

Wait what? The tracks aren't json files, they're .obj's. I use json files for saving the highscores and the unlocks

**Comment by ghost** [comment]
He ment the python files but ok.

**Comment by mandaw2014** [comment]
Ah ok, sorry I misunderstood
